version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voice-ai-web
    command: chmod +x voiceAI/start.sh
      ./voiceAI/start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - voice-ai-net

  postgres:
    image: postgres:16
    container_name: voice-ai-postgres
    environment:
      POSTGRES_DB: voice_ai_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - voice-ai-net

  redis:
    image: redis:7
    container_name: voice-ai-redis
    ports:
      - "6379:6379"
    networks:
      - voice-ai-net

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: voice-ai-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   
      - "15672:15672"
    networks:
      - voice-ai-net

volumes:
  postgres_data:

networks:
  voice-ai-net:
    driver: bridge
