version: "3.9"

services:
  web:
    image: voice-ai-web:latest
    container_name: voice-ai-web
    command: >
      sh -c "
      ./wait-for-it.sh postgres:5432 --strict --timeout=60 &&
      ./wait-for-it.sh redis:6379 --strict --timeout=60 &&
      ./wait-for-it.sh rabbitmq:5672 --strict --timeout=60 &&
      ./start.sh
      "

    working_dir: /app/voiceAI
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - voice-ai-net

  postgres:
    image: postgres:16
    container_name: voice-ai-postgres
    environment:
      POSTGRES_DB: voice_ai_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - voice-ai-net

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    depends_on:
      - postgres
    ports:
      - "6432:6432"
    networks:
      - voice-ai-net
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt

  redis:
    image: redis:7
    container_name: voice-ai-redis
    ports:
      - "6379:6379"
    networks:
      - voice-ai-net

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: voice-ai-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   
      - "15672:15672"
    networks:
      - voice-ai-net

volumes:
  postgres_data:

networks:
  voice-ai-net:
    driver: bridge
